/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FlashRouteImport } from './routes/flash'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'
import { Route as OrcamentosIdReciboRouteImport } from './routes/orcamentos.$id.recibo'
import { Route as ApiPublicSupabaseConfigRouteImport } from './routes/api/public/supabase-config'
import { Route as ApiPublicGoogleConfigRouteImport } from './routes/api/public/google-config'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashRoute = FlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrcamentosRoute,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OrcamentosRoute,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrcamentosRoute,
} as any)
const OrcamentosIdReciboRoute = OrcamentosIdReciboRouteImport.update({
  id: '/recibo',
  path: '/recibo',
  getParentRoute: () => OrcamentosIdRoute,
} as any)
const ApiPublicSupabaseConfigRoute = ApiPublicSupabaseConfigRouteImport.update({
  id: '/api/public/supabase-config',
  path: '/api/public/supabase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleConfigRoute = ApiPublicGoogleConfigRouteImport.update({
  id: '/api/public/google-config',
  path: '/api/public/google-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/backup': typeof BackupRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/flash': typeof FlashRoute
  '/fornecedores': typeof FornecedoresRoute
  '/mais': typeof MaisRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/termos': typeof TermosRoute
  '/orcamentos/$id': typeof OrcamentosIdRouteWithChildren
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/api/public/google-config': typeof ApiPublicGoogleConfigRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
  '/orcamentos/$id/recibo': typeof OrcamentosIdReciboRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/backup': typeof BackupRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/flash': typeof FlashRoute
  '/fornecedores': typeof FornecedoresRoute
  '/mais': typeof MaisRoute
  '/termos': typeof TermosRoute
  '/orcamentos/$id': typeof OrcamentosIdRouteWithChildren
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/orcamentos': typeof OrcamentosIndexRoute
  '/api/public/google-config': typeof ApiPublicGoogleConfigRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
  '/orcamentos/$id/recibo': typeof OrcamentosIdReciboRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/backup': typeof BackupRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/flash': typeof FlashRoute
  '/fornecedores': typeof FornecedoresRoute
  '/mais': typeof MaisRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/termos': typeof TermosRoute
  '/orcamentos/$id': typeof OrcamentosIdRouteWithChildren
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/api/public/google-config': typeof ApiPublicGoogleConfigRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
  '/orcamentos/$id/recibo': typeof OrcamentosIdReciboRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/backup'
    | '/clientes'
    | '/configuracoes'
    | '/flash'
    | '/fornecedores'
    | '/mais'
    | '/orcamentos'
    | '/termos'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos/'
    | '/api/public/google-config'
    | '/api/public/supabase-config'
    | '/orcamentos/$id/recibo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/backup'
    | '/clientes'
    | '/configuracoes'
    | '/flash'
    | '/fornecedores'
    | '/mais'
    | '/termos'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos'
    | '/api/public/google-config'
    | '/api/public/supabase-config'
    | '/orcamentos/$id/recibo'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/backup'
    | '/clientes'
    | '/configuracoes'
    | '/flash'
    | '/fornecedores'
    | '/mais'
    | '/orcamentos'
    | '/termos'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos/'
    | '/api/public/google-config'
    | '/api/public/supabase-config'
    | '/orcamentos/$id/recibo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BackupRoute: typeof BackupRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FlashRoute: typeof FlashRoute
  FornecedoresRoute: typeof FornecedoresRoute
  MaisRoute: typeof MaisRoute
  OrcamentosRoute: typeof OrcamentosRouteWithChildren
  TermosRoute: typeof TermosRoute
  ApiPublicGoogleConfigRoute: typeof ApiPublicGoogleConfigRoute
  ApiPublicSupabaseConfigRoute: typeof ApiPublicSupabaseConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash': {
      id: '/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof FlashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/orcamentos/$id/recibo': {
      id: '/orcamentos/$id/recibo'
      path: '/recibo'
      fullPath: '/orcamentos/$id/recibo'
      preLoaderRoute: typeof OrcamentosIdReciboRouteImport
      parentRoute: typeof OrcamentosIdRoute
    }
    '/api/public/supabase-config': {
      id: '/api/public/supabase-config'
      path: '/api/public/supabase-config'
      fullPath: '/api/public/supabase-config'
      preLoaderRoute: typeof ApiPublicSupabaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-config': {
      id: '/api/public/google-config'
      path: '/api/public/google-config'
      fullPath: '/api/public/google-config'
      preLoaderRoute: typeof ApiPublicGoogleConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrcamentosIdRouteChildren {
  OrcamentosIdReciboRoute: typeof OrcamentosIdReciboRoute
}

const OrcamentosIdRouteChildren: OrcamentosIdRouteChildren = {
  OrcamentosIdReciboRoute: OrcamentosIdReciboRoute,
}

const OrcamentosIdRouteWithChildren = OrcamentosIdRoute._addFileChildren(
  OrcamentosIdRouteChildren,
)

interface OrcamentosRouteChildren {
  OrcamentosIdRoute: typeof OrcamentosIdRouteWithChildren
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
}

const OrcamentosRouteChildren: OrcamentosRouteChildren = {
  OrcamentosIdRoute: OrcamentosIdRouteWithChildren,
  OrcamentosNovoRoute: OrcamentosNovoRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
}

const OrcamentosRouteWithChildren = OrcamentosRoute._addFileChildren(
  OrcamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BackupRoute: BackupRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FlashRoute: FlashRoute,
  FornecedoresRoute: FornecedoresRoute,
  MaisRoute: MaisRoute,
  OrcamentosRoute: OrcamentosRouteWithChildren,
  TermosRoute: TermosRoute,
  ApiPublicGoogleConfigRoute: ApiPublicGoogleConfigRoute,
  ApiPublicSupabaseConfigRoute: ApiPublicSupabaseConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
